import type { Metadata } from "next";
import { Raleway, Merriweather } from "next/font/google"
import "./globals.css";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-raleway'
})

const merriwether = Merriweather({
  subsets: ['latin'],
  weight: ["300", "400", "700", "900"],
  variable: '--font-merriwether'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${raleway.variable} ${merriwether.variable} font-primary`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
